sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: X0VRWB84w6MfvS9HnPHNWIJTyfdryKP8tY7CmgSSlc7OvDtKH/QidDVKOyUqaV5IRb2WCWY1Ow5pEJhLwoWirxFKGtwN8wr9I2SxkBL8GFfYREVfu0fxyaZ6Q97U6I61qr1GlFIXCLmQOIIU0FrRH+YyvmNBPApNmr/PpPLVtb51j5mBpOuuOeMfojC2DysYjjXJ9Zg6CXFOquBln4mFkFJi72SDT0wxdv0KPPPkqTUXIW0TBZ7RArNKp4p67f03Cu/sZOIS5r6jxzU46nPU7MoXbGmQ8LmrOPYq1s2BcAEXmv7GBSgxfyuDZiodzMFQbRLB/d3v4qaPylZJwCRrDfP6spFjVXFYc9f81m9iZEE9AdITnb8KkPTB6a0FGP/keI5LMSGz+lJpfWc2fy9moWWcrsPh+61Uxya4V4C3RbPrnUA2uvTy4L6PLM9YuiaRrYf57nbpLb7QVD2CD9+jiwpwe1wMZhoCFso57wdlZLExe5vjZ211OJRZanf44vpleELBzcn6Lkniaw6PunBJ90F1zug65j13m7+05Q9ptsQJScCaJ7P/UchSGP2LqWBYtMAJkfiPgZmFfuWrmg/EZiJchTb7U3JrNrAsR+WbvnYVFFI29yBSbKsbS/TP5Ky5i8L4Et/AAqXmv16VdGNhunFOmAPm7ZFG01i8OMdZv6Q=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Ten-Days-That-Shook-the-World_3076
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy